apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-api
    version: {{ .Values.color }} 
  name: test-api-{{ .Values.color }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: test-api
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: test-api
        version: {{ .Values.color }} 
    spec:
      containers:
      - name: test-api
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
        ports:
        - containerPort: 8080