apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  namespace: practice-rust
spec:
  selector:
    matchLabels:
      app: test-api
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
      - name: test-api
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
        ports:
        - containerPort: 8080