apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: practicerust
build:
  local:
    useBuildkit: true
    push: true
  artifacts:
    - image: iyamayuki/test-api
      context: .
      docker:
        dockerfile: app/Dockerfile
    - image: iyamayuki/test-web
      context: .
      docker:
        dockerfile: web/Dockerfile
deploy:
  helm:
    releases:
    - name: test-api
      chartPath: helm/Charts/test-api
      valuesFiles:
      - helm/Charts/test-api/values.yaml
      version: 1.0.0
      setValues: 
        image: iyamayuki/test-api
    - name: test-web
      chartPath: helm/Charts/test-web
      valuesFiles:
      - helm/Charts/test-web/values.yaml
      version: 1.0.0
      setValues: 
        image: iyamayuki/test-web
