apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: practicerust
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: iyamayuki/test-api
      context: .
      docker:
        dockerfile: app/Dockerfile
    - image: iyamayuki/test-web
      context: .
      docker:
        dockerfile: web/Dockerfile
deploy:
  helm:
    releases:
    - name: namespaces
      chartPath: helm/Charts/namespaces
      valuesFiles:
      - helm/Charts/namespaces/values.yaml
      version: 1.0.0
    - name: test-api-blue
      chartPath: helm/Charts/test-api/app
      valuesFiles:
      - helm/Charts/test-api/app/values.yaml
      version: 1.0.0
      setValues: 
        image: iyamayuki/test-api
        color: blue
    - name: test-api-green
      chartPath: helm/Charts/test-api/app
      valuesFiles:
      - helm/Charts/test-api/app/values.yaml
      version: 1.0.0
      setValues: 
        image: iyamayuki/test-api
        color: green
    - name: test-api-networking
      chartPath: helm/Charts/test-api/networking
      valuesFiles:
      - helm/Charts/test-api/networking/values.yaml
      version: 1.0.0
    - name: test-web-blue
      chartPath: helm/Charts/test-web/app
      valuesFiles:
      - helm/Charts/test-web/app/values.yaml
      version: 1.0.0
      setValues: 
        image: iyamayuki/test-web
        color: blue
    - name: test-web-green
      chartPath: helm/Charts/test-web/app
      valuesFiles:
      - helm/Charts/test-web/app/values.yaml
      version: 1.0.0
      setValues: 
        image: iyamayuki/test-web
        color: green
    - name: test-web-networking
      chartPath: helm/Charts//test-web/networking
      valuesFiles:
      - helm/Charts/test-web/networking/values.yaml
      version: 1.0.0
