apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: practicerust
build:
  artifacts:
    - image: test-api
      context: .
      docker:
        dockerfile: app/Dockerfile
deploy:
  helm:
    releases:
    - name: test-api
      chartPath: helm
      valuesFiles:
      - helm/values.yaml
      version: 1.0.0
      setValues: 
        image: test-api
