apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /hey
    route:
    - destination:
        host: test-web
        port:
          number: 80