apiVersion: v1
kind: Service
metadata:
  name: test-api-service
  namespace: practice-rust
spec:
  ports:
  - name: test-api-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  namespace: practice-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
      - image: iyamayuki/test-api:3df16d2-dirty
        imagePullPolicy: IfNotPresent
        name: test-api
        ports:
        - containerPort: 8080
        resources: null
---
apiVersion: v1
data:
  nginx.conf: |
    events {
        worker_connections 512;
    }

    http {
        upstream app {
            server test-api-service:8080;
        }
        server {
            listen 80 default_server;

            location / {
                root    /usr/share/nginx/html;
                index   index.html;
            }

            location /hey {
                proxy_pass http://app/hey;
            }

            location /echo {
                proxy_pass http://app/echo;
            }
        }
    }
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: practice-rust
---
apiVersion: v1
kind: Service
metadata:
  name: test-web-service
  namespace: practice-rust
spec:
  ports:
  - name: test-web-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
  namespace: practice-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
      - image: iyamayuki/test-web:3df16d2-dirty
        imagePullPolicy: IfNotPresent
        name: test-web
        ports:
        - containerPort: 80
        resources: null
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
      volumes:
      - configMap:
          name: nginx-conf
        name: nginx-conf
