apiVersion: v1
kind: Service
metadata:
  name: test-routing-service
spec:
  type: NodePort
  ports:
  - name: test-api-service
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: test-api
