apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-web-service
  namespace: {{ .Values.namespace }}
spec:
  host: test-web-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: blue
    labels:
      version: blue
  - name: green
    labels:
      version: green