apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-web-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test-web-service
        subset: {{ .Values.liveColor }}
        port:
          number: 80
