repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
    version: 1.16.0
    values:
      - istio-values.yaml

  - name: istiod
    namespace: istio-system
    createNamespace: true
    chart: istio/istiod
    version: 1.16.0
    values:
      - istio-values.yaml

  - name: istio-ingress
    namespace: practice-rust
    createNamespace: true
    chart: istio/gateway
    version: 1.16.0
