apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-api-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "test-api"
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test-api-service
        subset: {{ .Values.liveColor }}
        port:
          number: 8080
