apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-web
    version: {{ .Values.color }} 
  name: test-web-{{ .Values.color }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: test-web
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: test-web
        version: {{ .Values.color }}
    spec:
      containers:
      - name: test-web
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
      volumes:
      - configMap:
          name: nginx-conf-{{ .Values.color }}
        name: nginx-conf
