apiVersion: v1
kind: Service
metadata:
  name: test-web-service
  namespace: practice-rust
spec:
  type: NodePort
  ports:
  - name: test-web-service
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: test-web
