---
name: sync-helmfile
on:
  push:
    branches: [main]

jobs:
  skaffold:
    name: "install skaffold"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        run: ls -la
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Skaffold rendor
        run: skaffold render --digest-source=none --output manifests/manifest.yaml
      - name: push manifest
        run: |
          git config --global user.name "${GITHUB_ACTOR}" && \
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add . && \
          git commit -m "release" && \
          git pull -r --autostash && \
          git push

    