---
name: sync-helmfile
on:
  push:
    branches: [main]

jobs:
  skaffold:
    name: "install skaffold"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        run: ls -la
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Skaffold rendor
        run: skaffold render --offline=true --loud=true --output --digest-source=none manifests/manifest.yaml
        # run: skaffold render > manifests/manifest.yaml
      # - name: Test
      #   run: cat manifests/manifest.yaml
    