---
name: sync-helmfile
on:
  push:
    branches: [main]

jobs:
  skaffold:
    name: "install skaffold"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Skaffold rendor
        run: skaffold render --output manifests/manifest.yaml
      - name: push manifest
        run: |
          git config --global user.name "${GITHUB_ACTOR}" && \
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add manifests && \
          git commit -m "release" && \
          git pull -r --autostash && \
          git push

    