---
name: sync-helmfile
on:
  push:
    branches: [main]

jobs:
  skaffold:
    name: "skaffold"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ls -la
      - run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/